
dist: focal

arch:
  - amd64

services:
  - docker

os: linux

language: shell

notifications:
  email:
    - team@appwrite.io

before_install:
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
install:
  - docker --version
  - docker build -t appwrite-base-test .

script:
  - container-structure-test test --image appwrite-base-test --config tests.yaml

deploy:
  - provider: script
    edge: true
    script: docker run --rm --privileged linuxkit/binfmt:v0.8 &&
      docker buildx create --use &&
      docker buildx build --platform linux/amd64,linux/arm64/v8,linux/ppc64le -t appwrite/base:$TRAVIS_TAG ./ --push
    on:
      tags: true
      condition: "$TRAVIS_CPU_ARCH = amd64"